# Generated by Django 2.2.19 on 2021-04-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210402_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
